server:
  port: 8081
  errorResponse:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: BankApplication
  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:h2:mem:///bankdb
    username: admin
    password: admin
  datasource:
    url: jdbc:h2:mem:bankdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  h2.console:
    enabled: true
    path: /h2-console
    port: 8082

api:
  endpoint:
    person: /api/v1/persons/
    client: /api/v1/clients/
    account: /api/v1/accounts/
    movement: /api/v1/movements/
    report: /api/v1/reports/

logging:
  level:
    com.devsu: DEBUG